package com.main.hotel.mybatis.dao;

import com.main.hotel.mybatis.model.Hotel;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    Hotel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    List<Hotel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int updateByPrimaryKey(Hotel record);
}