package com.main.hotel.mybatis.dao;

import com.main.hotel.mybatis.model.Reservation;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    Reservation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    List<Reservation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int updateByPrimaryKey(Reservation record);
}