package com.main.hotel.mybatis.dao;

import com.main.hotel.mybatis.model.Room;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    Room selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    List<Room> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Wed Apr 06 00:45:22 EEST 2022
     */
    int updateByPrimaryKey(Room record);
    List<Room> selectRoomsForHotel(Integer id);
}